* Introduction

The iVM-app is the SW module that is stored on the long-term storage medium and will be used in the future to decode the digital content stored after iVM boot. This app needs to be transcribed from the film and be feed into the iVM machine memory. The application is self extracting to save storage space and minimize the amount of manual typing needed to bootstrap the machine.

iVM-app modules:
 - *Initial program*: Program that is started by the virtual machine and decompresses the rest of the application. 
 - *Unboxer*: Decodes images read from the image input device and return a bitstream and status codes.
 - *AFS*: Archival file system, organises the frames on film into files.
 - *Assembler*: Assembles decoded images into files.
 - *File decoder*: Decodes files from the assembler and renders them to one or more of the iVM output devices. The file decoder are using stadardized open source decoders and adapting the to iVM use.

Modules the user needs to provide:
 - *iVM implementation*: Implementation of iVM spesification With support for starting iVM-app from memory or file. The iVM must communicate with an image source device, feeding digitized images into the iVM and it must implement output devices support the formats provided by the iVM spesification.
 - *iVM execution environment*: Operation system or similar where the iVM runs. 
 - *Image source device*: Device capable of digitizing the frames on the storage medium.

#+BEGIN_SRC ditaa 
                    +----------------+
                    | iVM-app        |
                    |                |
                    |                |
                    |                |
  +--------+        +----------------+         +--------+
  | image  |        | iVM            |         | I/O    |
  | source |        | implementation |         | device |
  | device |        |                |         |        |
  |        +------->+                +<------->+        |
  +--------+        +----------------+         +--------+
                    | execution      |
                    | environment    |
                    +----------------+
#+END_SRC

* Boxing and AFS library

Core libraries for decoding frames and assembling frames into files.

** Boxing

 - iVM repo: https://github.com/preservationvm/boxing
 - Source: libtiff-v4.1.0 from https://github.com/piql/boxing
 - Compiling: CC=ivm64-gcc  CFLAGS="-DBOXING_USE_C99_LIBRARIES" ./configure --host ivm64 --prefix=<path>/ivm-apps/boxing

** AFS

 - iVM repo: https://github.com/preservationvm/afs
 - Source: libtiff-v4.1.0 from https://github.com/piql/afs
 - Compiling: CC=ivm64-gcc CFLAGS="-DBOXING_USE_C99_LIBRARIES" ./configure --host ivm64 --prefix=<path>/ivm-apps/boxing  LIBBOXING_DIR=<path>/ivm-apps/boxing


* File format decoders

The file format decoders are based on standardized open-source components and slightly modified so it complies with the iVM-compiler.

Since the iVM is not POSIX file system compilant, the libraries used cannot use any kind of file I/O. Similar, the iVM does not support multithreading so the library must be able to compile as a single threaded library. 

The libraries should be configured using ~--prefix <path>/ivm-apps/file-format-decoders/~, so that a ~make install~ will install the libraries in a folder where the ivm-app expects to find them.

** ZLIB

 - Source: http://www.zlib.net/zlib-1.2.11.tar.gz
 - Compiling: CC=ivm64-gcc ./configure --static --prefix=<path>/ivm-apps/file-format-decoders

** TIFF 

 - iVM repo: https://github.com/preservationvm/tiff-v4.1.0
 - Source: libtiff-v4.1.0 from https://download.osgeo.org/libtiff
 - Compiling: CC=ivm64-gcc ./configure --host ivm64 --prefix=<path>/ivm-apps/file-format-decoders


** PDF
CC=ivm64-gcc cmake \
 -DBUILD_GTK_TESTS=OFF \
 -DBUILD_QT5_TESTS=OFF\
 -DBUILD_CPP_TESTS=OFF\
 -DENABLE_SPLASH=OFF\
 -DENABLE_UTILS=OFF\
 -DENABLE_CPP=OFF\
 -DENABLE_GLIB=OFF\
 -DENABLE_GOBJECT_INTROSPECTION=OFF\
 -DENABLE_GTK_DOC=OFF\
 -DENABLE_QT5=OFF\
 -DENABLE_LIBOPENJPEG=none\
 -DENABLE_CMS=none\
 -DENABLE_DCTDECODER=none\
 -DENABLE_LIBCURL=OFF\
 -DENABLE_ZLIB=OFF\
 -DENABLE_ZLIB_UNCOMPRESS=OFF\
 -DBUILD_SHARED_LIBS=OFF\
 -DRUN_GPERF_IF_PRESENT=OFF\
 ..  

* iVM IO

Utility library for interfacing the iVM I/O devices.

* Building

#+BEGIN_SRC sh

# Get code
git clone https://github.com/preservationvm/ivm-apps.git
git clone https://github.com/preservationvm/boxing.git
git clone https://github.com/preservationvm/afs.git
git clone https://github.com/preservationvm/tiff-v4.1.0
wget http://www.zlib.net/zlib-1.2.11.tar.gz
tar xJf zlib-1.2.11.gz 

# Build - edit script to disable cross compiling
./build-libs.sh

# Build apps
./build-apps.sh

#+END_SRC
