#!/bin/bash

# Generate input.h file containing the compressed input as an array
# Usage: gen_input <input>

if [ $# -lt 1 ]; then
    echo "No input file given"
    exit 1
fi
if [ ! -f $1 ]; then
    echo "Input file not readable: $1"
    exit 1
fi
if [ ! -x /usr/bin/xz ]; then
    echo "/usr/bin/xz not found"
    exit 1
fi
if [ ! -x /usr/bin/xxd ]; then
    echo "/usr/bin/xxd not found"
    exit 1
fi

INPUT=$1
shift

TEMPFILE=$(mktemp "tmpXXXXXXXXXXXX")
SIZE=$(ls -l "$INPUT" | cut -d' ' -f5)

xz -c -C crc32 "$INPUT" > "$TEMPFILE"
xxd -i "$TEMPFILE" | sed "s/$TEMPFILE/input/" > input.h
rm -f "$TEMPFILE"
echo "int decompressed_size = $SIZE;" >> input.h
